id: IF62E7F40
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-02-20T12:08:36+00:00'
last_modified: '2022-06-15T13:55:42.438528+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG8900
  title: གསུང་འབུམ། ངག་དབང་ཆོས་གྲགས། ༼རྫོང་སར་ཁམས་བྱེའི་གློག་ཀླད་པར་མ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A126:
      image_group_id: I1KG8989
      title: Volume 1 of gsung 'bum/_ngag dbang chos grags/ (rdzong sar khams bye)
      total_pages: 602
      order: 1
      base_file: A126.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
