id: IF62E7F40
legacy_id: P000280
ocr_import_info:
  bdrc_scan_id: W1KG8900
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T16:52:03'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T18:12:09.333038+00:00'
last_modified: 2022-09-01 02:13:40.585569
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG8900
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG8900
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། ངག་དབང་ཆོས་གྲགས། ༼རྫོང་སར་ཁམས་བྱེའི་གློག་ཀླད་པར་མ།༽
  author: ས་སྐྱ་ཡོངས་འཛིན་ངག་དབང་ཆོས་གྲགས།
statistics:
  ocr_word_mean_confidence_index: 0.9507029275524701
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG8992:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG8992
      total_pages: 672
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1KG8992.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9466394843879743
    legacy_id: v004
  I1KG8994:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG8994
      total_pages: 660
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I1KG8994.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9554992320983764
    legacy_id: v006
  I1KG8989:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG8989
      total_pages: 602
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG8989.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9542196886964864
    legacy_id: v001
  I1KG8993:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG8993
      total_pages: 566
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I1KG8993.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9500837303183597
    legacy_id: v005
  I1KG8990:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG8990
      total_pages: 604
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG8990.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9452647085747619
    legacy_id: v002
  I1KG8991:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG8991
      total_pages: 722
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG8991.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9513164330685937
    legacy_id: v003
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
